### ISSUE TITLE
Add CMake as an alternative to configure

### ISSUE THREAD

**Issue by DigitalInBlue** [OpenDDS/OpenDDS#1016]
Having just spent far too long attempting to get the OpenDDS ```configure``` script to find my ```vcpkg```-installed ACE, Xerces, Qt, etc.  I am requesting that a ```CMakeLists.txt``` is written to build OpenDDS.  This would replace custom tooling with CMake-based tooling, still allow cross-platform support, and bring the building of the library into line with a growing number of open-source C++ projects all while making the library easier to build and configure.

**Comment by jwillemsen** [comment]
For vcpkg xercesc and openssl we enhanced the support see 
https://github.com/DOCGroup/MPC/pull/76

**Comment by DigitalInBlue** [comment]
I appreciate the help and may ask for more, but I would still suggest integrating CMake.  It is designed to solve a problem that you are attempting to solve in a custom way with custom scripts.  Using CMake would not only make the project easier to build and deploy, but would align the entire process with a growing industry-standard way of solving a problem; not requiring any special knowledge that must be gained just for this project.  Any user could get on with building and using the library vs. learning the special way to configure it before one even gets started.

Library configuration is not the focus of OpenDDS, so let that problem be solved by a project that was designed just for such a task.  Free up energy in the long run to reinvest into what makes OpenDDS what it is.

**Comment by jwillemsen** [comment]
It would be nice when we could use CMake, but the effort to do that for a project with the size of OpenDDS with all flexiblility built into MPC makes this a huge effort. We talk about hundreds of projects, when we add ACE/TAO we talk about thousands of projects that would have to be converted, an effort that takes man years which has to be funded by someone. There is cmake support on master for using OpenDDS, but using it for OpenDDS and all tests itself is really a huge effort. I am not against it, but we see that customers tend to fund features, not to fund a migration to a different build system.

**Comment by mitza-oci** [comment]
@DigitalInBlue I'll echo what Johnny said and also point out that we (Object Computing, Inc.) have made significant investments in CMake support including the new feature for using CMake to generate OpenDDS-using projects and a prototype of OpenDDS itself built using CMake.  

However please keep in mind the history of these projects (combining both ACE_TAO and OpenDDS).  Reading your comment one might think that the original authors of OpenDDS saw a C++ ecosystem with a mature CMake product that was widely adopted in diverse cross-platform projects.  That did not actually exist at the time.  OpenDDS was initially developed as an extension to TAO's orbsvcs so it made sense to follow ACE's build system.  So regardless of the technical merits of MPC vs CMake (and let's not have that discussion here), there are at least practical, nontechnical reasons for why things are as you see them.

As OpenDDS continues to grow in adoption and evolve in the current C++ ecosystem, there may very well be a future version that is configured and built using CMake.  If you'd like to contribute towards that goal (whether that be code or funding), we'd welcome that contribution.  Based on our experience with the CMake prototype we have a document with what we learned (issues, challenges, next steps) that can be the basis for future development.

**Comment by iguessthislldo** [comment]
#4203 added CMake as an alternative build system and will be available in 3.26.0. That addresses the title. For the actual issue, I'm not exactly sure how this works with vcpkg, but I can't imagine it would be hard. Probably #1074 is better for that discussion. I'm going to go ahead and close this.

**Comment by DigitalInBlue** [comment]
Thank you!  This is great news.
