### ISSUE TITLE
Fail to extract partially downloaded ACE+TAO-2.2a_with_latest_patches_NO_makefiles.tar.gz

### ISSUE THREAD

**Issue by ajkerzner** [OpenDDS/OpenDDS#1032]
To reproduce: (1) run the configure script, (2) interrupt the script with CTRL-C while it's downloading ACE+TAO-2.2a_with_latest_patches_NO_makefiles.tar.gz, and (3) re-run the configure script with the same arguments.

This is not a bug, but it could be a little smoother.

One option is to checksum the downloaded file using [the checksum file](http://download.ociweb.com/TAO-2.2a/TAO-2.2a.md5). This could be problematic on a closed network, but it'd verify that you have a complete copy of the latest archive of ACE+TAO. Perhaps another option to enable this behavior?

The second option is to download the file as maybe ACE+TAO-2.2a_with_latest_patches_NO_makefiles.tar.gz.tmp, and rename after completion. Therefore, if the tempfile exists, you most likely have a partial download - you could resume the download (may be bad if another patch to ACE+TAO is made after first partial download), or redownload the entire thing.

This could apply to curl, wget, and whatever is used on Windows.

**Comment by jwillemsen** [comment]
Or we could put a sha512 of the package we need to download into the configure script, that can work for the DOC group version of TAO, we have a known package we download

**Comment by mitza-oci** [comment]
I would be fine with downloading to a temporary file and then renaming.  I don't know that a checksum is necessary here, there's a lot more complexity to manage.

**Comment by jwillemsen** [comment]
For the DOC group version we also provide a md5 file for download on github, this could be used to check the md5 of the package downloaded

**Comment by mitza-oci** [comment]
Corresponding md5 is here: http://download.ociweb.com/TAO-2.2a_patches/patch15.md5

**Comment by iguessthislldo** [comment]
Since both distributions have md5 files available and Perl has a md5 core module, it seems like that is the way to go.

**Comment by iguessthislldo** [comment]
As part of #4327, the configure script will now be able do an MD5 check of the ACE/TAO archive. If it fails then it will remove the archive and try to download to download it again.
