### ISSUE TITLE
Late joining reader using TRANSIENT_DURABILITY_QOS doesn't work

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#2083]
We have a setup with a writer and late joining reader. We are using keyed data, at the moment the writer has written all samples the reader starts and after some seconds he performs a lookup_instance but doesn't get any instance handle back, looks the `instance_map_` within the reader is empty. 

From the OpenDDS log I can see that data is received by the reader at a lower level, but looks it doesn't end up in the instance_map_
[latereader.txt](https://github.com/objectcomputing/OpenDDS/files/5573246/latereader.txt)

**Comment by jwillemsen** [comment]
DataWriter uses RELIABLE_RELIABILITY_QOS, TRANSIENT_DURABILITY_QOS, KEEP_ALL_HISTORY_QOS
DataReader uses RELIABLE_RELIABILITY_QOS, TRANSIENT_LOCAL_DURABILITY_QOS, KEEP_ALL_HISTORY_QOS

**Comment by simpsont-oci** [comment]
What version are you using?

**Comment by jwillemsen** [comment]
Master

**Comment by jwillemsen** [comment]
When this is something you think should work, let me know, making a new unit test for this is on my todo list when you say it should work

**Comment by mitza-oci** [comment]
Which transport type is used for this?

**Comment by jwillemsen** [comment]
We are using RTPS

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/blob/f3dcfa53ad01914259fc2535ae43e2f1326b8c86/docs/design/RTPS#L25

**Comment by jwillemsen** [comment]
Ok, so not implemented yet, any idea how large an effort to add this would be?

**Comment by jwillemsen** [comment]
I did some retests today and this now looks to work (at least a high level test depending on this now works), is that correct?
