### ISSUE TITLE
publisher no buffer space available

### ISSUE THREAD

**Issue by hyeinkwon798** [OpenDDS/OpenDDS#2374]
when i run pub
after several seconds away it has an error

RtpsUdpSendStrategy :: send_single_i() failed send: No buffer space available

i used ACE_OS::sleep(1) but it is to slow for video 

Will there be any way to do it???

**Comment by jrw972** [comment]
Please fork the OpenDDS repo, add an example under `tests/DCPS` that illustrates the problem, and create a pull request.
