### ISSUE TITLE
RTPSDiscovery doesn't use GET_CONFIG_VALUE macros

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#2797]
RTPSDiscovery does do its own handling of the configuration values (https://github.com/objectcomputing/OpenDDS/blob/045cde5cb9e4a01d8291917ba4a1527feb071e88/dds/DCPS/RTPS/RtpsDiscovery.cpp#L102), where other parts do use the `GET_CONFIG_VALUE` macros, which put at least some logging in the log file that values are override by the user. 

Would also help when the user overriden value is added to the log, makes it easier to see what the user did configure at the end

**Comment by jrw972** [comment]
OBE with ConfigStore.
