### ISSUE TITLE
Cannot set output path of the files generated from IDL using cmake

### ISSUE THREAD

**Issue by aelfisha** [OpenDDS/OpenDDS#3899]
When using OPENDDS_TARGET_SOURCES cmake macro, the user can select the output folder where the generated source will be stored.
This can be done using the "-o" option of "TAO_IDL_OPTIONS" and "OPENDDS_IDL_OPTIONS" arguments.
Example:

```cmake
OPENDDS_TARGET_SOURCES(${MY_TARGET} ${FILE_NAME}
            TAO_IDL_OPTIONS -o ${DDS_IDL_GEN_DIR} -I${DDS_IDL_DIR}
            OPENDDS_IDL_OPTIONS -o ${DDS_IDL_GEN_DIR} -I${DDS_IDL_DIR})
```

This is no longer possible, as the -o is ignored by mistake.
The root cause is highlighted in the below snapshot taken from version 3.22 from cmake function "opendds_target_idl_sources"
![image](https://user-images.githubusercontent.com/81911545/204426687-c7e0a6d0-fbae-4827-8956-5c16af5341eb.png)

The variable used to select the output path "_idl_cmd_arg_-o" is different from the one that is used to parse the input "_ddsidl_cmd_arg_-o"

**Comment by mitza-oci** [comment]
Please use a pull request to add a test case for this feature
