### ISSUE TITLE
When domain participant for a specific domain id is destroyed then created again, any data sent using its new publishers/subscriber are send with the old guid

### ISSUE THREAD

**Issue by aelfisha** [OpenDDS/OpenDDS#4019]
When domain participant for a specific domain id is destroyed then created again, any data sent using its new publishers/subscriber are send with the old guid.

Imagine the below scenario:
1. Assume that there is an application already running that has already created a domain participant, subscriber and a data reader for a topic <x>
2. Now imagine the below scenario on the application that publishes the data:
2.a. Create a domain participant with domain id 40.
2.b. Create a publisher using domain participant created in point 2.a.
2.c. Create a data writer using publisher created in point 2.b.
2.d. Write data using the data writer => The data will be received by the subscriber application, **no problem in this scenario**
2.e. We delete the data writer, publisher, domain participant and recreate them with the same exact parameters as before.
2.f. Write data using the data writer => The data is not received by the subscriber application, **problematic scenario**.

What happens is that the data writer, publisher are created with a new guid, but when data is serialized, the guid that ends up in the serialized data is the old guid and not the new one so the data gets ignored by the subscriber.

This is applicable when rtps is used (no rtps relay)

**Comment by mitza-oci** [comment]
There is a limitation of the `rtps_udp` transport type that each instance can only be used by a single DomainParticipant.  Applications with multiple DomainParticipants (even if those participants aren't in use simultaneously) should create multiple transport instances using one of these strategies:
* directly via API calls to the transport registry
* using the configuration file explicit configuration of needed instances
* using the "Configuration Templates" feature (see section 7.5 in developer's guide) to have the middleware create transport instances on demand

**Comment by aelfisha** [comment]
I think what you mentioned in different from what i am trying to describe.

The application create a domain participant for domain id 40 then deleted that domain participant and after some time created another domain participant using the same domain id 40. I do not think that this counts as multiple domain participants.
