### ISSUE TITLE
‘servant_to_reference’ is not a member of ‘OpenDDS::DCPS’ in OpenDDS 3.22

### ISSUE THREAD

**Issue by wzr1337** [OpenDDS/OpenDDS#4029]
The following code leads to an error:

```cpp
    // Create a dynamicObject listener
    DynamicsObjectDataReaderListenerImpl dynamicsobject_listener_servant;

    DDS::DataReaderListener_var dynamicsobject_listener =
      ::OpenDDS::DCPS::servant_to_reference(&dynamicsobject_listener_servant);

    if (CORBA::is_nil (dynamicsobject_listener.in ()))
    {
      cerr << "DynamicsOobject listener is nil." << endl;
      ACE_OS::exit(1);
    }
```

I have copied the code from the StockQuoter example and changed names, but the complaint is not about that. It is about missing support in OpenDDS 3.22 any clues for me?

```sh
src/subscriber.cpp:96:24: error: ‘servant_to_reference’ is not a member of ‘OpenDDS::DCPS’
   96 |       ::OpenDDS::DCPS::servant_to_reference(&dynamicsobject_listener_servant);
   ```

**Comment by iguessthislldo** [comment]
The article is out of date. There's no such thing as a `servant_to_reference` anymore and as far as I know you can't put stack allocated objects in `*_vars`. I would write:

```
    DDS::DataReaderListener_var dynamicsobject_listener = new DynamicsObjectDataReaderListenerImpl;
```

**Comment by iguessthislldo** [comment]
To add this, here is the equivalent line in the version we have kept updated in the repo:

https://github.com/OpenDDS/OpenDDS/blob/d1364a4bc77e02e6dc5b34612856caf408ccaabf/examples/DCPS/IntroductionToOpenDDS/subscriber.cpp#L120
