### ISSUE TITLE
Trouble compiling application when OpenDDS is installed to /usr

### ISSUE THREAD

**Issue by tmayoff** [OpenDDS/OpenDDS#4039]
I'm trying to package OpenDDS as a .deb package mainly for distributing to our own internal machines. However I ran into issues when testing installing OpenDDS with the prefix set to `/usr`, 

There's a bunch of errors like this

```
external/ROS2Types/sensor_msgs/msg/CameraInfoTypeSupportC.h:140:7: error: expected class-name before ‘{’ token
  140 |       {
      |       ^
```

This seems to be caused because in the `HeaderTypeSupportC.h` files it seems to be missing includes

```
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "HeaderC.h"

# The includes below are missing when OpenDDS is installed to /usr
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
```

And this is the same for every other .idl file we try to compile as well

Compiled with these commands 
```
opendds_idl -o ... -Lc++11 -St ...
tao_idl -o ... -Sp -Sd -Sg -SS -Sa -St --idl-version 4 --unknown-annotations ignore ...
```

**Comment by mitza-oci** [comment]
I set up a docker container so I can install to `/usr` without impacting the rest of the system.  I'm trying it out now.

Does `HeaderTypeSupport.idl` have the corresponding IDL files included?  Is it similar to an in-tree file like `tests/DCPS/ConsolidatedMessengerIdl/MessengerTypeSupport.idl`?
```
#include "dds/DdsDcpsInfrastructure.idl"
#include "dds/DdsDcpsPublication.idl"
#include "dds/DdsDcpsSubscriptionExt.idl"
#include "dds/DdsDcpsTopic.idl"
#include "dds/DdsDcpsTypeSupportExt.idl"
```

**Comment by tmayoff** [comment]
I checked the TypeSupport.idl file and they were missing, turns out I hadn't updated DDS_ROOT location for the `-I/usr/local/include` arg in the call to `tao_idl`. There doesn't seem to an error or any output when those includes can't be found

**Comment by mitza-oci** [comment]
What was DDS_ROOT set to when it didn't work?  I know there's an error when it's not set at all.

**Comment by mitza-oci** [comment]
Just to get it recorded in the issue, this worked for me:
```
mkdir ok
DDS_ROOT=/usr/share/dds opendds_idl -St -Lc++11 -o ok Messenger.idl
tao_idl -Sp -Sd -Sg -SS -Sa -St --idl-version 4 --unknown-annotations ignore -I/usr/include -o ok ok/MessengerTypeSupport.idl
```

**Comment by mitza-oci** [comment]
> What was DDS_ROOT set to when it didn't work? I know there's an error when it's not set at all.

Now that I've tried it I think I understand what you meant here.  It's not that DDS_ROOT itself was wrong, it's that tao_idl didn't have a way to resolve those `#includes` (based on `-I`) and didn't produce an error.

**Comment by tmayoff** [comment]
Yeah sorry, I worded that awkwardly, but yes the -I was set incorrectly and tao_idl couldn't find the includes

**Comment by mitza-oci** [comment]
OK, let's close this one.  I'm not sure why `tao_idl` does this, but I haven't tried to reduce it to a simple test case to make it an issue in that repository.
