### ISSUE TITLE
Unable to use Ace.Init() in unity

### ISSUE THREAD

**Issue by RavenFoxx** [OpenDDS/OpenDDS#4044]
![image](https://user-images.githubusercontent.com/53256536/219345244-dc708bdc-b725-4850-b785-9cb0a215e2e0.png)
No matter where i called "Ace.Init();", it always returns the same error. Even without it (I know "Ace.Init();" needs to be called first before any other methods from OpenDDSharp is called), calling other methods from "OpenDDSharp" namespace returns the same error.
For the record, I have it in unity's default Awake method right now.

**Comment by mitza-oci** [comment]
Is this an issue about https://github.com/jmmorato/OpenDDSharp ?
