### ISSUE TITLE
Any plans to abandon/replace Xerces-c? 

### ISSUE THREAD

**Issue by jmccabe** [OpenDDS/OpenDDS#4070]
As in the subject, really. I've been looking at using Xerces-C over the last few days, mainly because we have to do some fiddling with XML data and, as it's needed for OpenDDS security (which we intend to use at some point), it seemed like I should use the same library.

It's pretty horrible, though, IMO. The documentation isn't great (actually, IMO, it's pretty poor), code samples are phenomenally ugly with inconsistent styling, and decent 3rd party (i.e other users') examples of doing things are not easy to find. Not only that, but the latest minutes of the steering group - https://whimsy.apache.org/board/minutes/Xerces.html - mention that retiring the project has been considered due to lack of development interest.

It seems like this may not be the best time for me to adopt some major component that's about to go the way of numerous other OSS I've used.

Does OpenDDS just use it due to ACE's dependency on it for XML features?

Your thoughts would be welcomed.

**Comment by mitza-oci** [comment]
> As in the subject, really. I've been looking at using Xerces-C over the last few days, mainly because we have to do some fiddling with XML data and, as it's needed for OpenDDS security (which we intend to use at some point), it seemed like I should use the same library.
> 
> It's pretty horrible, though, IMO. The documentation isn't great (actually, IMO, it's pretty poor), code samples are phenomenally ugly with inconsistent styling, and decent 3rd party (i.e other users') examples of doing things are not easy to find. Not only that, but the latest minutes of the steering group - https://whimsy.apache.org/board/minutes/Xerces.html - mention that retiring the project has been considered due to lack of development interest.
> 
> It seems like this may not be the best time for me to adopt some major component that's about to go the way of numerous other OSS I've used.
> 

> Does OpenDDS just use it due to ACE's dependency on it for XML features?

OpenDDS initially selected it because it was available on many platforms, (at least at the time) well-maintained, and there was experience using it on the development team (as seen in the fact that ACE_XML_Utils depends on it).

We do not have to keep using it, and the recent steering group minutes you pointed out may provide some motivation to switch.  Other drawbacks you mentioned are probably more concerning for new development (ease of use, styling, examples, docs) than for maintaining its use in OpenDDS.

**Comment by iguessthislldo** [comment]
Retiring Xerces is new to me, but not surprising. We've thought about at least supporting another XML parser library for a little while. I think RapidXML and TinyXML were among the ones we've thought about. All the Xerxes code for security is limited to [this directory](https://github.com/OpenDDS/OpenDDS/tree/master/dds/DCPS/security/AccessControl) and it's pretty isolated so it shouldn't be a difficult task to replace or add support for an alternative XML parser.

**Comment by jwillemsen** [comment]
Also xerces-c is also used for the QoS XML parsing (see https://github.com/OpenDDS/OpenDDS/tree/master/dds/DCPS/QOS_XML_Handler), that uses XSC (see https://github.com/DOCGroup/XSC) to generate a lot of the parsing code.

**Comment by jmccabe** [comment]
Many thanks for your replies. I can understand the "many platforms" argument entirely, and the pointers to your code have helped me see how you're using it, so have been helpful.

From my point of view, my aim was, as I mentioned, to use Xerces-C++ to avoid duplication of functionality, but I think I may be better off using something less powerful, and probably easier :-)

Thanks again; I'll close this as an issue (sorry I didn't raise it in the "Discussions" section which would've been more appropriate!).

**Comment by jwillemsen** [comment]
As part of AXCIOMA we also use Xerces-C++/XSC to parse the XML deployment plans. That is even more complex as the user can define any type in IDL for which they can set values in XML, see https://github.com/RemedyIT/dancex11/tree/master/tools/config_handlers
