### ISSUE TITLE
opendds_idl generates not compilable TypeSupport.idl when using <type>Seq in user IDL

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4110]
Opendds_idl generates not compilable  TypeSupport.idl

```
/home/johnny/ACE/OpenDDS/ACE_TAO/ACE/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I /home/johnny/ACE/OpenDDS/ACE_TAO/TAO --idl-version 4 --unknown-annotations ignore -as -Sa -St -I../../../.. complex_types.idl
/home/johnny/ACE/OpenDDS/bin/opendds_idl -Sa -St --no-dcps-data-type-warnings complex_types.idl
/home/johnny/ACE/OpenDDS/ACE_TAO/ACE/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I /home/johnny/ACE/OpenDDS/ACE_TAO/TAO --idl-version 4 --unknown-annotations ignore -as -Sa -St -I../../../.. complex_typesTypeSupport.idl
Error - /home/johnny/ACE/OpenDDS/ACE_TAO/ACE/bin/tao_idl: "complex_typesTypeSupport.idl", line 2079: redefinition after use, ::DDS_Native::SequenceTest::My_msg2Seq, ::DDS_Native::SequenceTest, ::DDS_Native::SequenceTest::My_msg2Seq
Error - /home/johnny/ACE/OpenDDS/ACE_TAO/ACE/bin/tao_idl: "complex_typesTypeSupport.idl", line 2279: redefinition after use, ::DDS_Native::SequenceTest::My_msg3Seq, ::DDS_Native::SequenceTest, ::DDS_Native::SequenceTest::My_msg3Seq
Error - /home/johnny/ACE/OpenDDS/ACE_TAO/ACE/bin/tao_idl: "complex_typesTypeSupport.idl", line 2679: redefinition after use, ::DDS_Native::SequenceTest::My_msg5Seq, ::DDS_Native::SequenceTest, ::DDS_Native::SequenceTest::My_msg5Seq
```

**Comment by jwillemsen** [comment]
See PR #4111, comment out the types starting at line 287 from complex_types.idl

**Comment by iguessthislldo** [comment]
Are you sure this worked before? That IDL is defining the same exact sequences for topic types as the type support does.

https://github.com/OpenDDS/OpenDDS/blob/15aecb09043351e2d6627386db739166f48ef4c9/tests/DCPS/Compiler/complex_types/complex_types.idl#L344-L349

**Comment by iguessthislldo** [comment]
I just tested this with 3.23.0 to make sure, and it does the same thing. As far as I see it the names of types generated in the TypeSupport.idl are basically reserved when a type is a topic type.

**Comment by jwillemsen** [comment]
Would be nice when this user IDL would be supported. I noticed this when working on the OpenDDS reproducer, but in AXCIOMA we do use `-Wb,opendds_sequence_suffix=OpenDDSSeq` to handle this name clash

**Comment by mitza-oci** [comment]
> Would be nice when this user IDL would be supported. I noticed this when working on the OpenDDS reproducer, but in AXCIOMA we do use `-Wb,opendds_sequence_suffix=OpenDDSSeq` to handle this name clash

I suggest opening a dedicated issue for this.

**Comment by jwillemsen** [comment]
Can’t we just use this issue?

**Comment by mitza-oci** [comment]
> Can’t we just use this issue?

Seems to be different to me since it's about what the spec requires.  This issue looks like it's reporting a regression.  But I suppose it doesn't matter that much which issue it's in, you can change the title.

**Comment by jwillemsen** [comment]
This happens because the user is also defining a FooSeq for type Foo in his own IDL, is common when he wants to use the sequence of Foo in another type

**Comment by mitza-oci** [comment]
#2966 and #2965 addressed these problems a about a year and half ago.  What changed since then?

**Comment by jwillemsen** [comment]
We do have the workaround, closing it now, no priority from our side
