### ISSUE TITLE
Mailings lists go through OCI

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4118]
On https://github.com/OpenDDS/OpenDDS/blob/gh-pages/support.md the mailing lists are mentioned, but that goes through OCI, shouldn't that be pointing to some page on opendds.org?

**Comment by mitza-oci** [comment]
It will, eventually

**Comment by jwillemsen** [comment]
See https://github.com/OpenDDS/OpenDDS/pull/4235
