### ISSUE TITLE
Scoreboard not regenerated anymore

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4147]
Looks http://scoreboard.ociweb.com/oci-dds.html is not generated anymore, maybe also add a link to the scoreboard from the readme?

**Comment by jwillemsen** [comment]
What about putting the scoreboard configuration xml under the OpenDDS organization? That way anyone can add builds

**Comment by mitza-oci** [comment]
Scoreboard configuration, as is done here https://github.com/DOCGroup/scoreboard, makes sense to be in a common place -- that allows any organization to easily contribute builds.
Autobuild configuration doesn't really need to be common.  The configuration of each build is typically output in its log, so it's not needed for visibility/traceability.

**Comment by jwillemsen** [comment]
New scoreboard is online at https://scoreboard.opendds.org/
