### ISSUE TITLE
Issue generating an Code using opendds_cxx11 and dcps_java

### ISSUE THREAD

**Issue by lozanoeg** [OpenDDS/OpenDDS#4224]
hello i'm trying to generate code using the cxx11 bindings and also use java but it after i get to the point to run make it fails to build. if i run the MPC file with only cxx11 it builds and if i run it only with dcps_java it builds but not both

**Comment by mitza-oci** [comment]
These are not compatible options.  Instead you can build two different libraries from the same IDL: one for use by the JVM and the other for C++.

**Comment by lozanoeg** [comment]
is this the case with doing the opendds_idl gen with -Lc++11 then using only dcps_java in the mpc as well?

**Comment by jrw972** [comment]
There are two C++ language mappings:  classic and C++11.  The Java bindings (`dcps_java`) assumes the classic mapping has been used.  Thus, `dcps_java` is incompatible with `cxx11`.

If you need both C++11 and Java then you will need to compile the IDL twice to produce different libraries.
