### ISSUE TITLE
IDL4 not supported annotations result in warning message with `error` in the message

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4225]
I am experimenting with the IDL4 extensions for the IDL to C++11 language mapping. When using the new `bit_bound` annotation as below I get the following output on the console

```
Warning - /home/johnny/ACE/OpenDDS/bin/opendds_idl: "BoundTest.idl", line 17: error in lookup of symbol: bit_bound
```

The word `error` now triggers the autobuild error handling resulting in red builds. At the moment an unsupported annotation is detected I think opendds_idl should give an information message, not warning or error, for example

```
Info - /home/johnny/ACE/OpenDDS/bin/opendds_idl: "BoundTest.idl", line 17: unknown annotation found: bit_bound
```

The test IDL has

```
  @bit_bound(32)
  enum EnumType {
    FIRST, SECOND, THIRD
  };
```

**Comment by iguessthislldo** [comment]
This comes from [tao_idl](https://github.com/DOCGroup/ACE_TAO/blob/a71b63addfb814c439e33d2b7a175c95609230e1/TAO/TAO_IDL/fe/idl.ypp#L2533-L2552), which I think is "warn once" by default. I think what you want is `--unknown-annotations ignore`.

**Comment by jwillemsen** [comment]
Thanks, will try that tomorrow

**Comment by jwillemsen** [comment]
Adding `--unknown-annotations ignore` silences the warning from opendds_idl
