### ISSUE TITLE
FastDDS（2.10版本）和OPENDDS（3.24.1版本）无法建立通信 

### ISSUE THREAD

**Issue by hong12234** [OpenDDS/OpenDDS#4268]
在局域网内部192.168.225.57为PC monitor，192.168.225.1为Tbox，192.168.225.32为IVI。Tbox和IVI无法通信，网络报文已经上传。再monitor中只能监视到Tbox  UDP传输方式。
对比查看初始化配置：
![e7b11f6d391204386a0c94a5ff597b5](https://github.com/OpenDDS/OpenDDS/assets/38304396/5efec7e9-f9d0-4df7-b5ed-638cba79a82c)
![010f82c371a90e7865134bbbdec2458](https://github.com/OpenDDS/OpenDDS/assets/38304396/44e5b888-03e5-49f0-bc53-e2184e74bea7)
![6880bc12905c67b2f892c84a6e5a261](https://github.com/OpenDDS/OpenDDS/assets/38304396/e7db724f-c9ef-4f80-8342-5e8ad08659f4)

![edc8d2a4687d69c5a795cc1d44b7d48](https://github.com/OpenDDS/OpenDDS/assets/38304396/5a7e74b4-d199-464f-96da-b22edc51c68e)

下面为网络包：
[log.zip](https://github.com/OpenDDS/OpenDDS/files/12574491/log.zip)

请问有可能是什么原因导致无法通信

**Comment by jrw972** [comment]
FYI https://github.com/OpenDDS/OpenDDS/issues/4245

**Comment by iguessthislldo** [comment]
Closing this issue since the FastDDS issue was closed.
