### ISSUE TITLE
Communication between opendds and fastdds Opendds sent data Fastdds did not receive it

### ISSUE THREAD

**Issue by hong12234** [OpenDDS/OpenDDS#4315]
Hello, I have caught both normal and abnormal network packets from both parties. The data type analysis is the same, but Fastdds cannot receive the data，Look at the picture,This is the log captured by sending and replying to the compound medicine separately.
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/bc185217-2e8e-4bef-919b-31ace4b7a88e)
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/a10fe31c-91e4-4531-8a01-7cbadcc9a0ef)
I still don't understand a question, why does fastdds reply with a dimainid of 115 instead of 1.Next, we will upload the network package。
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/8aa85962-0936-4090-839a-8b61d1dfc808)

[log.zip](https://github.com/OpenDDS/OpenDDS/files/13038317/log.zip)

**Comment by hong12234** [comment]
may I ask if RPTS2.2 and 2.4 protocols are compatible

**Comment by jrw972** [comment]
Is this the same as #4245?

**Comment by hong12234** [comment]
> [这和#4245](https://github.com/OpenDDS/OpenDDS/issues/4245)一样吗？

It should not be a problem. There is no subcontracting in the message. Currently, the other party is sending data, either a specific piece of data cannot be received, or the received data is inconsistent with the sent data

**Comment by Smazdaturet** [comment]
Ensure that you set openDDS to use XCDRv1 and not XCDRv2 as data representation, FastDDS does not support v2 yet (even 2.12.0). It WIP and will be implemented soon.

**Comment by mitza-oci** [comment]
> may I ask if RPTS2.2 and 2.4 protocols are compatible

All 2.x versions are designed to be compatible.

**Comment by hong12234** [comment]
> > 请问RPTS2.2和2.4协议是否兼容
> 
> 所有 2.x 版本均设计为兼容。

Thank you for your reply. It seems that the problem still lies in DDS data serialization

**Comment by hong12234** [comment]
> 确保将 openDDS 设置为使用 XCDRv1 而不是 XCDRv2 作为数据表示，FastDDS 尚不支持 v2（甚至 2.12.0）。它正在开发中，并将很快实施。

If it is already set, communication will not be possible, and not receiving data is not always possible, nor is it possible to receive all data. But I feel like there is still a problem with receiving data serialization

**Comment by hong12234** [comment]
Refer to this schematic diagram，
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/e4133595-0711-40a3-a9bd-b74c06d05564)
This data is two consecutive packets sent by Opendds.
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/b0af2373-c9b2-44fc-aba5-d8bc439c1332)
It can also be seen from the heartbeat packet that two packets of data have been written，Fastdds also received data.
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/b6dcfdb0-a4e6-4b68-bba0-ca779f2cc708)
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/750a18b2-d00f-48b1-b255-c10d4bb64de9)
I don't understand why two consecutive pieces of data are sent here.And the first packet of data is still incorrect

**Comment by hong12234** [comment]
Here, Oepndds sends a packet of data, analyzing the underlying interaction between heartbeat packets and ACK packets. At this point, it is reasonable to say that fastdds has already received the data, but in reality, fastdds on_data_available No functions were called。
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/b3988c82-f18c-4f65-ad0e-db9f93ea2255)
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/0974eb65-5839-4a6b-ace9-908f5d0e1ab5)

**Comment by hong12234** [comment]
[ivi_1019_03.zip](https://github.com/OpenDDS/OpenDDS/files/13059670/ivi_1019_03.zip)
This is the packet compression package shown in the screenshot above

**Comment by hong12234** [comment]
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/643cd030-2d29-44a6-9c84-6b3e247a04d2)
This is our data KEY idl setting

**Comment by jrw972** [comment]
From the packet capture:
* 584 is a DATA message from 010300557bb57df70d3accf8.00000002 which is an OpenDDS writer.  The sequence number is 15.
* 588 is a HEARTBEAT from 010300557bb57df70d3accf8.00000002 directed at 010f4169a109d24d00000000.00000207 which is a eProsima - Fast-RTPS reader.
* 589 is an ACK from 010f4169a109d24d00000000.00000207 to 010300557bb57df70d3accf8.00000002 for sequence number 15.

From an RTPS perspective, everything seems to be working correctly.  If the DCPS DataReader did not get the sample, then it most likely is a deserialization problem.  Check what encoding the reader expects and then configure OpenDDS to use that encoding.

**Comment by hong12234** [comment]
> 从抓包来看：
> 
> * 584 是来自 OpenDDS 编写器 010300557bb57df70d3accf8.00000002 的数据消息。序列号为15。
> * 588 是来自 010300557bb57df70d3accf8.00000002 的心跳，指向 010f4169a109d24d00000000.00000207，这是一个 eProsima - Fast-RTPS 阅读器。
> * 589 是序列号 15 的从 010f4169a109d24d00000000.00000207 到 010300557bb57df70d3accf8.00000002 的 ACK。
> 
> 从 RTPS 的角度来看，一切似乎都工作正常。如果 DCPS DataReader 未获取样本，则很可能是反序列化问题。检查读者期望的编码，然后配置 OpenDDS 以使用该编码。

Thank you for your reply. Currently, it seems that the problem is caused by the @ key keyword, but there may still be instances where Opendds sends incorrect data. It is unclear what caused the issue.

**Comment by hong12234** [comment]
![image](https://github.com/OpenDDS/OpenDDS/assets/38304396/7d3edaa7-875f-4bc9-aeca-ace59f6f44d6)
I'm not sure what this data is and where it was sent. The application layer only called it once

**Comment by jrw972** [comment]
`@key` defines the key of the instance.  Both sides must agree on the key.
Message 31 looks like an instance registration message.
See `register_instance` in the DDS spec for background.

**Comment by hong12234** [comment]
> `@key`定义实例的键。双方必须就密钥达成一致。 消息 31 看起来像是实例注册消息。 请`register_instance`参阅 DDS 规范了解背景信息。

谢谢你的回复。
