### ISSUE TITLE
build opendds on windows with gcc(minGW)

### ISSUE THREAD

**Issue by shaozhihua** [OpenDDS/OpenDDS#4363]
hi guys,
I want to build opendds on windows with mingw,because my work environment is not support visual studio, as now,opendds and tao+ace it is very convenient with visual studio,I really need the help build with gcc,is there any efficient way to build?
thanks very much.

**Comment by jwillemsen** [comment]
Seems to triggered https://github.com/DOCGroup/ACE_TAO/issues/2164

**Comment by shaozhihua** [comment]
that is my first step,I think ace.dll.a and tao.dll.a is the dependency of the opendds.I think.

**Comment by iguessthislldo** [comment]
Yes, you'll have to be able to build ACE/TAO before building OpenDDS. OpenDDS doesn't officially support MinGW though as you might already know. It should be possible, but you'll have to try it and work through any issues.

I don't really have much experience with MinGW, but I can say once ACE/TAO is built, you have a few ways to approach this.

1. You can configure OpenDDS manually without the `configure` script. It can be build using `mwc.pl` like ACE/TAO can, but it requires more work as you have to do what the `configure` script is doing.
2. You can modify the `configure` script to support MinGW. Based on #1762, it doesn't work right now as is.
3. You can try building [OpenDDS with CMake](https://opendds.readthedocs.io/en/master/devguide/building/index.html#cmake-building). You'd have to use `-DOPENDDS_ACE=<path>` to point to the ACE you already built as the CMake scripts have no idea how to build ACE/TAO itself for MinGW. You'll also have to pass `-G "MinGW Makefiles"` to CMake.

**Comment by shaozhihua** [comment]
I give up .I choose the greatest compiler in the universe ：Visual Studio.
what can I do,just this.
thanks for everyone ,thanks.

**Comment by iguessthislldo** [comment]
> I give up .I choose the greatest compiler in the universe ：Visual Studio.
no,the greatest IDE in the universe.

I don't know about that, but if you can use it and it works, then sure.

**Comment by shaozhihua** [comment]
> > I give up .I choose the greatest compiler in the universe ：Visual Studio.
> > no,the greatest IDE in the universe.
> 
> I don't know about that, but if you can use it and it works, then sure.

thanks IguessthisIdo，thanks anyway。
