### ISSUE TITLE
Issue While Cross-Compiling IDL Libraries for Android Platform

### ISSUE THREAD

**Issue by Nidheesh123** [OpenDDS/OpenDDS#4403]
I had followed the build process mentioned in [https://opendds.readthedocs.io/en/dds-3.26.1/devguide/building/android.html#android-java-idl-libs] for building OpenDDS in Android platform. After configuring and building I had tried to build the IDL libraries for getting type supported files for android using following command,
"**source $DDS_ROOT/setenv.sh; opendds_mwc.pl && PATH=$PATH:$TOOL_CHAIN/bin make**" 
But this got failed with following messages,
"_Skipping TAO_QtResource (QtResource.mpc); it requires dummy_label.
Skipping dissector (dissector.mpc); it requires wireshark_any.
DeepDownReference_wq.mpc: line 1:
ERROR: Unable to locate parent: DeepDownReference_paths
ERROR: Unable to process build/target/tools/modeling/tests/Deep/Down/Reference/DeepDownReference.mpc
ERROR: Unable to process: default input"_

The steps that I have followed is as follows,
1. Downloaded OpenDDS source from git using -  git clone https://github.com/OpenDDS/OpenDDS.git.
2. ./configure --doc-group3 --target=android --macros=android_abi=arm64-v8a --macros=android_api=31 --macros=android_ndk=/home/Android/Sdk/ndk/26.1.10909125 --macros=android_sdk=/home/Android/Sdk --macros=android_target_api=31 --java=/usr/lib/jvm/default-java
3. make -j4
4. source $DDS_ROOT/setenv.sh; opendds_mwc.pl && PATH=$PATH:/home/quest/WorkSpace/Tool-chain/toolchain/bin make

After steps 4, my thought was the generated .jar files will contain all the necessary class files and type supported files for running publisher and subscriber in android device. Please help me to solve this issue and please assist me if anything else I have to do for making this success in android platform.
[Build environment]
Ubuntu 20.04

**Comment by mitza-oci** [comment]
In step 4, change to the directory for your project IDL.

**Comment by Nidheesh123** [comment]
Thank you very much @mitza-oci for your reply. 

I changed the directory to "OpenDDS/DevGuideExamples/DCPS/Messenger" folder and run the command and the error gone. And after that I copied all the four .jar files and .so files into the android libs and native-libs folder of my android app. My intention is to develop a publisher app using OpenDDS by referring the following link because I couldn't found any other sample android projects,
"https://opendds.readthedocs.io/en/latest/devguide/java_bindings.html" 

But still the type supported files not getting in android source code, for example "MessageTypeSupportImpl, MessageDataWriterHelper etc".  Could you please clarify do I need to follow any other steps for getting this objects in android code ?

**Comment by mitza-oci** [comment]
> Thank you very much @mitza-oci for your reply.
> 
> I changed the directory to "OpenDDS/DevGuideExamples/DCPS/Messenger" folder and run the command and the error gone.

Instead of using DevGuideExamples/DCPS/Messenger, start with one of the Java tests that creates a JAR file from the generated code.  The use of OpenDDS's Java Bindings is described in the developer's guide section devoted to Java.

There is an example Android application here https://github.com/OpenDDS/opendds-smart-lock/tree/master/android

**Comment by Nidheesh123** [comment]
Thanks @mitza-oci for you prompt support.

Meanwhile I already checked this Smart Lock Sample but I couldn't see the publisher-subscriber code there, so that I tried to build the Messenger app for android.  

Now I was able to build all the .so files and .jar files for creating sample publisher and subscriber code in android platform. 

The current issue I facing is when the publisher app starts it got crashed with the following error,

"**E  (12352|12352) ERROR: InfoRepoDiscovery::get_dcps_info: unable to narrow DCPSInfo (file://repo.ior) for key DEFAULT_REPO.**"
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nidheesh.openddspublishapp/com.nidheesh.openddspublishapp.MainActivity}: java.lang.NullPointerException: dpf.create_participant(…ATUS_MASK.value) must not be null

It will be really helpful if you know the root cause of this issue.

**Comment by mitza-oci** [comment]
> Meanwhile I already checked this Smart Lock Sample but I couldn't see the publisher-subscriber code there, 

I'm not sure what you mean by this.  The Smart Lock is a complete Android application that we developed and open sourced for the community to use.

> so that I tried to build the Messenger app for android.
> 
> Now I was able to build all the .so files and .jar files for creating sample publisher and subscriber code in android platform.
> 
> The current issue I facing is when the publisher app starts it got crashed with the following error,

This seems like a new issue, it's not about compiling IDL libraries.
The error you saw is not specific to Android.  I'm guessing it has been discussed many time before.

**Comment by Nidheesh123** [comment]
@mitza-oci  Thanks for your response.

> I'm not sure what you mean by this. The Smart Lock is a complete Android application that we developed and open sourced for the community to use.
Sorry for the mistake, now I checked this Smart Lock app code based on that I had modified my android code for publisher app. 
Based on that could you please clarify the following 2 issues,
1. When I run the app it shows all the **.pem** files and **.p7s** files were missing, from where these files can be added.
2. After launching the app it got crashed with following error,
**"java.lang.UnsatisfiedLinkError: No implementation found for long Messenger.MessageTypeSupportImpl._jni_init() (tried Java_Messenger_MessageTypeSupportImpl__1jni_1init and Java_Messenger_MessageTypeSupportImpl__1jni_1init__)"**

Please clarify above queries if you can.

**Comment by mitza-oci** [comment]
1. This is unrelated to the question, please open a new issue.  My suggestion would be to run without DDS Security at first.
2. Using the Java test application from the OpenDDS repo, the function that the JVM is looking for is present in my build:
```
$ nm java/tests/messenger/messenger_idl/libmessenger_idl_test.so | grep jni_1init
000000000005f683 T Java_Messenger_MessageTypeSupportImpl__1jni_1init
```

**Comment by Nidheesh123** [comment]
@mitza-oci Thanks for your feedback.

I had added the native library file "**libmessenger_idl_test.so**" from path "java/tests/messenger/messenger_idl" to my android app fodler "/src/main/jniLibs/**arm64-v8a**" and the library is dynamically loaded using the android api **System.loadLibrary("messenger_idl_test")**. But when the app starts is got crashed with following error,

"java.lang.UnsatisfiedLinkError: dlopen failed: library "libmessenger_idl_test.so" not found"

I had checked the architecture of this .so file, and it is shows as,
_libmessenger_idl_test.so: ELF 64-bit LSB shared object, **ARM aarch64**, version 1 (SYSV), dynamically linked, BuildID[sha1]=5bfc777831c6a4caf35728ec4d654e0af06a9b8c, with debug_info, not stripped_

Please help me if you know the root cause of this issue

**Comment by Nidheesh123** [comment]
@mitza-oci  Thanks for your feedback.

As per your response I had used the "libmessenger_idl_test.so" library file from "test/messenger/messenger_idl/" app to my android app under the folder "src/main/jniLibs/arm64-v8a/ folder. And also called the "System.loadLibrary("messenger_idl_test")" api for invoking the native library from an application class (There is no error or crash observed).

But after that app crashes with the following logs,
"No implementation found for long com.nidheesh.openddspublishapp.messenger.MessageTypeSupportImpl._jni_1init() (tried Java_com_nidheesh_openddspublishapp_messenger_MessageTypeSupportImpl__1jni_11init and Java_com_nidheesh_openddspublishapp_messenger_MessageTypeSupportImpl__1jni_11init__)" 

As I already mentioned the OpenDDS is build with the following configuration,
./configure --doc-group3 --target=android --macros=android_abi=arm64-v8a --macros=android_api=31 --macros=android_ndk=/home/quest/Android/Sdk/ndk/26.1.10909125 --macros=android_sdk=/home/quest/Android/Sdk --macros=android_target_api=31 --java=/usr/lib/jvm/default-java

So the abi of library file "libmessenger_idl_test.so" will be ARM aarch64, but why this methods were not getting accessed at runtime. I had checked the content of library using following command,
_nm libmessenger_idl_test.so | grep jni_1init_
and the result shows as,
00000000000ac248 T Java_Messenger_MessageTypeSupportImpl__1jni_1init

Please help me if anything further that I have to do for fixing this issue.

**Comment by Nidheesh123** [comment]
@mitza-oci Thanks for your feedback.

Based on your response I had copied libmessenger_idl_test.so file into my android apps and now the exceptions were gone. Now the subscriber app can receive the messages sent by the publisher app when both apps are in same device. But if both apps are in different device the communication not working.
Could you clarify for the intercommunication between two devices any other settings has to be handled or any additional field has to be added in config.ini file.

Currently my subscriber and publisher app has the same config.ini file like as follows,
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS
[transport/the_rtps_transport]
transport_type=rtps_udp
[domain/1]
DiscoveryConfig=DiscoveryConfig1

**Comment by mitza-oci** [comment]
Please start a new discussion topic for this
https://github.com/OpenDDS/OpenDDS/discussions
