### ISSUE TITLE
Configure script compiler detection clang/clang++ inconsistency

### ISSUE THREAD

**Issue by mitza-oci** [OpenDDS/OpenDDS#4439]
There's still the issue of this `elsif ($opts{'compiler'} =~ /g\+\+/) { # GCC or Clang` not working for when `clang` is detected as the compiler rather than `clang++`.

Also maybe this can be split into it's own issue + PR for discussion

_Originally posted by @tmayoff in https://github.com/OpenDDS/OpenDDS/issues/4364#issuecomment-1904949160_

**Comment by tmayoff** [comment]
It worked when I removed `clang` completely I didn't try putting it at the end
