### ISSUE TITLE
Missing news

### ISSUE THREAD

**Issue by jrw972** [OpenDDS/OpenDDS#4460]
- [x] Add news for #4451
- [x] Add news for #4450

**Comment by iguessthislldo** [comment]
- #4426
- #4424 (I guess?)
- #4411
- #4376
- #4355
- #4339
- #4449

**Comment by iguessthislldo** [comment]
See here for the what we currently have on master: https://opendds.readthedocs.io/en/master/news.html#v3-27-0

**Comment by jrw972** [comment]
@sonndinh Can you add a news item for #4376 to #4468?
@mitza-oci Can you add a news item for #4449 to #4468?

**Comment by mitza-oci** [comment]
> @mitza-oci Can you add a news item for #4449 to #4468?

✅
