### ISSUE TITLE
Generate "key only" versions of vread and vwrite

### ISSUE THREAD

**Issue by jrw972** [OpenDDS/OpenDDS#4543]

**Comment by sonndinh** [comment]
My thought is to generate the following additional functions:
```
bool vwrite(ValueWriter& value_writer, const KeyOnly<T>& sample);
boo vwriter(ValueWriter& value_writer, const NestedKeyOnly<T>& sample);
bool vread(ValueReader& value_reader, KeyOnly<T>& sample);
bool vread(ValueReader& value_reader, NestedKeyOnly<T>& sample);
```
The ones that work with `KeyOnly<T>` are only needed for topic types. Their behaviors are similar to the counterparts for the insertion and extraction operations. That is `vwrite` will write only the key fields from the sample; `vread` will assume the input stream has only key fields and skip any extra fields that are not key.

`ValueDispatcher` will need to be inspected for any changes needed.

**Comment by jrw972** [comment]
This seems reasonable.
