### ISSUE TITLE
Memory leak problem when using reader->get_topicdescription()->get_type_name()

### ISSUE THREAD

**Issue by NawTun** [OpenDDS/OpenDDS#4566]
I used the following statement in the ReaderListenerImpl::on_data_available to get the topic type name.
`const char* type_name = reader->get_topicdescription()->get_type_name();` 
I found that the memory occupied by the process has been growing. 
After debugging, I found that the function get_type_name has been allocating memory, but the allocated memory does not seem to be released. Do I need to release it manually, or should I use another function to obtain the type name?

**Comment by jwillemsen** [comment]
See https://opendds.readthedocs.io/en/latest-release/devguide/getting_started.html#registering-the-data-type-and-creating-a-topic

**Comment by NawTun** [comment]
Thanks so much！
