### ISSUE TITLE
Not supported OCI ACE/TAO distro in scripts

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4639]
At https://github.com/OpenDDS/OpenDDS/blob/bfc7c0324da52de2c5208d320d267954125b0dab/tools/scripts/gitrelease.pl#L43 there are some URL/filenames for the OCI ACE/TAO distro which isn't supported anymore, needs some cleanup

**Comment by iguessthislldo** [comment]
Yes, but it is only used by the Doxygen step. There wasn't a reason to change it because we dropped OCI TAO and stopped generating Doxygen at basically the same time. We haven't permanently decided what to do with Doxygen, so I view this as part of #4114.
