### ISSUE TITLE
IDL compilation requires dds/OpenDDSConfig.h

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4670]
When compiling using github master I now get the errors below, looks `dds/OpenDDSConfig.h` is now required to compile an IDL file, but this should be optional, https://github.com/OpenDDS/OpenDDS/pull/4498 was merged in the past to allow this for C++

```
/home/build/jenkins/workspace/fc_axcioma_acetao_mpc_opendds_master/BUILD/DOC_ROOT/ACE/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I /home/build/jenkins/workspace/fc_axcioma_acetao_mpc_opendds_master/BUILD/DOC_ROOT/TAO -DGEN_IDL_MAKE_DEPS --idl-version 4 --unknown-annotations ignore -as -DOPENDDS_NO_MULTI_TOPIC -Sa -St -Wb,versioning_begin=OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL -Wb,versioning_end=OPENDDS_END_VERSIONED_NAMESPACE_DECL -Wb,versioning_include=dds/Versioned_Namespace.h -Wb,pch_include=DCPS/DdsDcps_pch.h -Wb,export_macro=OpenDDS_Dcps_Export -Wb,export_include=dds/DCPS/dcps_export.h -SS -I.. DdsSecurityParams.idl
In file included from ../dds/OpenDDSConfigWrapper.idl:9,
                 from DdsSecurityParams.idl:13:

../dds/OpenDDSConfigWrapper.h:15:12: fatal error: dds/OpenDDSConfig.h: No such file or directory

   15 | #  include <dds/OpenDDSConfig.h>
      |            ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

See https://download.remedy.nl/buildlogs/fc_opendds_versioned/ for a build with the same error

**Comment by jwillemsen** [comment]
As I am using MPC based generation, would it be possible to add a MPC feature to disable this include? Just like I use `multi_topic=0` in `default.features` to disable multi topic support

**Comment by jwillemsen** [comment]
In our environment C++17 is mandatory, so we could also use `__has_include` (https://en.cppreference.com/w/cpp/preprocessor/include)

**Comment by jwillemsen** [comment]
Using `__has_include` doesn't seem possible as that define is not part of the tao_idl arguments

**Comment by mitza-oci** [comment]
See release notes in docs/news.d/_releases/v3.28.0.rst -- at this point I think it would be easier to have the build script simply do the equivalent of `touch dds/OpenDDSConfig.h`

**Comment by jwillemsen** [comment]
Just a touch isn’t easy when building axcioma, it is lot of tooling we have, a mpc feature is much easier to automate with our setup

**Comment by mitza-oci** [comment]
I think doing it in the general case is as simple, since that would need to check if the file already exists.

In the use case you described before, you know that the file doesn't exist.  So that simple `<%cp%>` could either exist outside of OpenDDS or it could be enabled by an MPC feature.

**Comment by jwillemsen** [comment]
Easiest for users is a mpc feature in the OpenDDS core mpc file, will help anyone who uses mpc directly without configure

**Comment by jwillemsen** [comment]
Or just use my PR, that works for axcioma and I can set that feature easy in the builds

**Comment by mitza-oci** [comment]
I assume there is a recent PR that broke the behavior you expected.  Please link that PR# here and it would be good to set up a CI build that matches your specific use case so this doesn't happen again.

**Comment by mitza-oci** [comment]
> Or just use my PR, that works for axcioma and I can set that feature easy in the builds

I don't think there would be a problem merging #4671 - I added comments here just because I was wondering if there was a simpler way to handle it (not requiring a change to the MPC feature).

**Comment by jwillemsen** [comment]
C++17 would make this really easy ;-)
