### ISSUE TITLE
configure failed with errorcode 255

### ISSUE THREAD

**Issue by ahkharsha** [OpenDDS/OpenDDS#4690]
I'm trying to run the configure script, but it keeps saying
"ERROR: unknown host msys, stopped at configure line 637.
ERROR: configure failed with errorcode 255"

I have installed strawberry perl and msys2. I am super new to this, so could anyone help me figure out whats wrong with it? What other details do I need to provide? I'll edit the question and add more details!

**Comment by mitza-oci** [comment]
https://opendds.readthedocs.io/en/latest-release/devguide/quickstart/windows.html
