### ISSUE TITLE
FACE: Warning on sending/receiving octet sequence

### ISSUE THREAD

**Issue by AlexFalzone** [OpenDDS/OpenDDS#4728]
I am encountering a problem with OpenDDS/FACE. I would like to understand if it is a problem related to my code or something else. 
I am trying to send/receive an octet bigger like some MB (20/30) but the subscriber receives the warning:

> (320|325) WARNING: DataReaderImpl::accept_sample_processing - subscription 01030242.ac110004.0140cfe1.00000007(c3b64124) failed to find publication data for 01030242.ac110003.07330527.00000002(1a743bfa)

Followed by  the return_code set to:

> FACE::NOT_AVAILABLE

I found out that adding a sleep right after the send may fix the issue. The thing that I wish to know is if that is normal (for example it is caused by the large size of the octet) or if it is caused somehow by my code.

**Comment by jrw972** [comment]
Can you create a PR that modifies `DevGuideExamples/FACE/Simple` to behave like your test program?

**Comment by AlexFalzone** [comment]
The problem happens only when I send a large sequence<octet>. 
I tried to replicate the behavior in `DevGuideExamples/FACE/Simple` but could not reproduce the problem.
