### ISSUE TITLE
Support page update?

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#4765]
At https://github.com/OpenDDS/OpenDDS/blob/gh-pages/support.md the mailing lists are listed under resources, but they point to a OCI webpage, something to remove/update?

**Comment by jwillemsen** [comment]
Also maybe clarify the OpenDDS Foundation at the top, that the foundation is itself a support provider, so that it is not the community, maybe the terms&conditions should also say OpenDDS Foundation?

**Comment by iguessthislldo** [comment]
Related, on the OCI page, the "Documentation" link points to the old PDF devguide.
