### ISSUE TITLE
Allow IDL Annotations to process uint32_t for enum values

### ISSUE THREAD

**Issue by Markaeus** [OpenDDS/OpenDDS#4781]
When you process an IDL Annotation values (ie. @value)t assumes you're using int32, should this be allowed to include uint32 as well as others for enums?

**Comment by mitza-oci** [comment]
An example of using `@value` is in `dds/DCPS/RTPS/RtpsSubmessageKind.idl`.  Would you please share a snippet of IDL that shows what you're trying to do?

`opendds_idl` currently supports int32 since that's what the XTypes spec uses for IDL enumerators (see Table 4).
