### ISSUE TITLE
Check that domain id's are supported by RTPS

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#638]
Coming from review of PR #632, we should check the domain id

Domain IDs above 231 are not supported by RTPS Discovery (see docs/design/RTPS and devguide).

**Comment by mitza-oci** [comment]
Should probably just be a warning.  It will work with a larger number but the port mapping is undefined.  Both the DCPS and RTPS specs leave a lot up to the implementation which makes defining what should be an error difficult.

**Comment by jrw972** [comment]
Closed by #4655
